// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "Demo",
  platforms: [
    .iOS("16")
  ],
  products: [
    .iOSApplication(
      name: "Demo",
      targets: ["App"],
      bundleIdentifier: "dev.to4iki.MultiModuleSample.Demo",
      teamIdentifier: "SJ4J2CMQ6B",
      displayVersion: "1.0",
      bundleVersion: "1",
      appIcon: .placeholder(icon: .tv),
      accentColor: .presetColor(.orange),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ]
    )
  ],
  dependencies: [
    .package(
      name: "Package", path: "/Users/to4iki/src/github.com/to4iki/multi-module-sample/AppPackage")
  ],
  targets: [
    .executableTarget(
      name: "App"
    )
  ]
)
